version: '3.8'

services:

  rabbitmq:
    image: rabbitmq:3.11.0-management
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    restart: unless-stopped

volumes:
  rabbitmq_data:
