version: '3.8'

services:

  rabbitmq:
    image: rabbitmq:3.11.0-management
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: unless-stopped

  common-db:
    image: postgres:14.5
    volumes:
      - common-db_data:/var/lib/postgresql
    ports:
      - "5432:5432"
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${COMMON_DB_NAME}
      - POSTGRES_USER=${COMMON_DB_USER}
      - POSTGRES_PASSWORD=${COMMON_DB_PASSWORD}

volumes:
  rabbitmq_data:
  common-db_data:
